#!/bin/bash

wallpapersdir=$HOME/images/wallpapers

sleep 300
while true; do
    randomwp=$(ls $wallpapersdir | shuf | head -1)
    randomwp=$wallpapersdir/$randomwp

    # echo $randomwp
    swww img --transition-fps 60 --transition-type fade $randomwp
    
    # 10 min = 600
    sleep 1200
done
